[nonce]
frog-1-lutron-lights-avg-kw = 1492658400.0
frog-1-exterior-lights-kwh = 1492658400.0
"frog-2-zone-humidity-2-%" = 1492658400.0
"frog-1-duct-return-humidity-%" = 1492658400.0
weather-station-dry-bulb-temp-c = 1492658400.0
weather-station-wind-direction-deg = 1492658400.0
frog-2-air-handler-kwh = 1492658400.0
frog-1-whole-building-avg-kw = 1492658400.0
frog-2-wall-temp-1-f = 1492658400.0
frog-2-solar-2-kw = 1492658400.0
frog-1-ceiling-fans-avg-kw = 1492658400.0
frog-2-zone-temp-1-f = 1492658400.0
frog-1-building-services-it-kw = 1492658400.0
frog-1-solar-1-kw = 1492658400.0
"frog-2-duct-supply-humidity-%" = 1492658400.0
"frog-2-zone-humidity-3-%" = 1492572104.1361842
frog-1-air-handler-kw = 1492658400.0
frog-2-co2-ppm = 1492658400.0
frog-2-window-actuators-kw = 1492658400.0
frog-1-exterior-lights-avg-kw = 1492658400.0
frog-2-lutron-lights-avg-kw = 1492658400.0
frog-1-chiller-avg-kw = 1492658400.0
frog-2-exterior-lights-kw = 1492658400.0
frog-2-lutron-lights-kwh = 1492658400.0
frog-2-window-actuators-avg-kw = 1492658400.0
frog-1-co2-ppm = 1492658400.0
frog-2-solar-1-avg-kw = 1492658400.0
frog-1-wall-temp-3-f = 1492658400.0
weather-station-dewpoint-c = 1492658400.0
frog-1-duct-supply-temp-f = 1492658400.0
frog-2-service-lights-kwh = 1492658400.0
frog-2-solar-1-kw = 1492658400.0
"frog-1-zone-humidity-3-%" = 1492572104.1361842
frog-2-whole-building-kwh = 1492658400.0
frog-1-exterior-lights-kw = 1492658400.0
frog-1-air-handler-avg-kw = 1492658400.0
frog-1-service-lights-kwh = 1492658400.0
frog-1-fire-alarm-avg-kw = 1492658400.0
"frog-2-zone-humidity-1-%" = 1492658400.0
frog-2-fire-alarm-kw = 1492658400.0
frog-2-window-actuators-kwh = 1492658400.0
frog-1-zone-temp-2-f = 1492658400.0
"frog-1-zone-humidity-2-%" = 1492658400.0
frog-2-zone-temp-2-f = 1492658400.0
frog-2-whole-building-kw = 1492658400.0
frog-1-ceiling-fans-kwh = 1492658400.0
frog-1-light-lux = 1492658400.0
frog-1-building-services-it-kwh = 1492658400.0
frog-2-ceiling-fans-kw = 1492658400.0
frog-1-solar-2-avg-kw = 1492658400.0
frog-1-dry-bulb-temp-f = 1492658400.0
frog-1-solar-2-kwh = 1492658400.0
frog-2-light-lux = 1492658400.0
frog-1-lutron-lights-kw = 1492658400.0
frog-1-solar-1-kwh = 1492658400.0
frog-1-lutron-lights-kwh = 1492658400.0
frog-2-service-lights-kw = 1492658400.0
frog-2-ceiling-fans-kwh = 1492658400.0
frog-2-chiller-kw = 1492658400.0
frog-2-fire-alarm-avg-kw = 1492658400.0
frog-1-building-services-avg-kw = 1492658400.0
frog-2-zone-temp-3-f = 1492572104.1361842
frog-2-air-handler-kw = 1492658400.0
frog-1-air-handler-kwh = 1492658400.0
frog-1-zone-temp-1-f = 1492658400.0
frog-2-solar-2-avg-kw = 1492658400.0
frog-2-air-handler-avg-kw = 1492658400.0
frog-1-window-actuators-kwh = 1492658400.0
frog-2-solar-2-kwh = 1492658400.0
"weather-station-humidity-%" = 1492658400.0
frog-1-whole-building-kwh = 1492658400.0
frog-2-service-lights-avg-kw = 1492658400.0
frog-2-chiller-avg-kw = 1492658400.0
frog-1-duct-return-temp-f = 1492658400.0
frog-2-building-services-kw = 1492658400.0
weather-station-solar-radiation-wm-2 = 1492572104.1361842
frog-2-exterior-lights-kwh = 1492658400.0
frog-2-solar-1-kwh = 1492658400.0
frog-2-wall-temp-2-f = 1492658400.0
"frog-1-humidity-%" = 1492658400.0
"frog-1-duct-supply-humidity-%" = 1492658400.0
frog-2-wall-temp-3-f = 1492658400.0
frog-1-fire-alarm-kwh = 1492658400.0
frog-2-duct-supply-temp-f = 1492658400.0
frog-1-ceiling-fans-kw = 1492658400.0
frog-1-window-actuators-avg-kw = 1492658400.0
"frog-2-humidity-%" = 1492658400.0
frog-2-fire-alarm-kwh = 1492658400.0
frog-1-wall-temp-1-f = 1492658400.0
frog-2-ceiling-fans-avg-kw = 1492658400.0
frog-2-chiller-kwh = 1492658400.0
"frog-2-duct-return-humidity-%" = 1492658400.0
frog-2-building-services-it-avg-kw = 1492658400.0
weather-station-barometric-pressure-hpa = 1492658400.0
frog-2-whole-building-avg-kw = 1492658400.0
"frog-1-zone-humidity-1-%" = 1492658400.0
frog-1-chiller-kwh = 1492658400.0
frog-1-solar-1-avg-kw = 1492658400.0
frog-2-lutron-lights-kw = 1492658400.0
frog-2-building-services-it-kwh = 1492658400.0
frog-2-globe-temp-f = 1492658400.0
frog-2-dry-bulb-temp-f = 1492658400.0
frog-1-chiller-kw = 1492658400.0
frog-2-duct-return-temp-f = 1492658400.0
frog-1-service-lights-kw = 1492658400.0
frog-1-globe-temp-f = 1492658400.0
frog-1-service-lights-avg-kw = 1492658400.0
frog-2-exterior-lights-avg-kw = 1492658400.0
frog-1-solar-2-kw = 1492658400.0
frog-1-fire-alarm-kw = 1492658400.0
frog-1-whole-building-kw = 1492658400.0
"weather-station-wind-speed-m/s" = 1492658400.0
frog-1-window-actuators-kw = 1492658400.0
frog-1-wall-temp-2-f = 1492658400.0
frog-1-zone-temp-3-f = 1492572104.1361842
