[sensor]
sub-map = "node"
ignore = []

[sensor.frog-1]
fire-alarm-avg = 91
duct-supply-humidity = 2
duct-supply-temp = 14
service-lights = 55
air-handler-avg = 86
whole-building = 64
zone-humidity-1 = 3
service-lights-avg = 93
window-actuators = 65
exterior-lights-avg = 90
zone-temp-1 = 19
solar-1 = 62
solar-2-avg = 95
wall-temp-1 = 16
globe-temp = 15
ceiling-fans-avg = 88
wall-temp-3 = 18
window-actuators-avg = 97
CO2 = 81
solar-1-avg = 94
whole-building-avg = 96
exterior-lights = 59
light = 78
solar-2 = 63
zone-humidity-2 = 4
lutron-lights = 61
zone-temp-2 = 20
chiller = 58
chiller-avg = 89
fire-alarm = 60
wall-temp-2 = 17
duct-return-temp = 13
duct-return-humidity = 1
building-services-avg = 87
building-services-it = 56
air-handler = 54
lutron-lights-avg = 92
ceiling-fans = 57
other-avg = 98

[sensor.frog-2]
fire-alarm-avg = 104
duct-supply-humidity = 6
duct-supply-temp = 22
service-lights = 67
air-handler-avg = 99
whole-building = 76
zone-humidity-1 = 7
service-lights-avg = 106
window-actuators = 77
exterior-lights-avg = 103
zone-temp-1 = 24
solar-1 = 74
solar-2-avg = 108
wall-temp-1 = 25
globe-temp = 23
ceiling-fans-avg = 101
wall-temp-3 = 27
window-actuators-avg = 110
building-services = 44
CO2 = 82
solar-1-avg = 107
whole-building-avg = 109
exterior-lights = 71
light = 79
solar-2 = 75
zone-humidity-2 = 8
lutron-lights = 73
zone-temp-2 = 28
chiller = 70
chiller-avg = 102
building-services-it-avg = 100
fire-alarm = 72
wall-temp-2 = 26
duct-return-temp = 21
duct-return-humidity = 5
building-services-it = 68
air-handler = 66
lutron-lights-avg = 105
ceiling-fans = 69
other-avg = 111

[sensor.weather-station]
wind-direction = 12
humidity = 9
dewpoint = 11
wind-speed = 80
barometric-pressure = 29
dry-bulb-temp = 10
solar-radiation = 83
